In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

df = pd.read_csv("house_regression_lab_dataset(in).csv")
x= df[["Area_sqft", "Bedrooms", "Age_years"]]
y = df["Price_lakhs"]

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

model = LinearRegression()

model.fit(
    x_train,
    y_train
)
y_pred = model.predict(x_test)
print("The predicted prices  are :",y_pred)


mae = mean_absolute_error(
    y_test,
    y_pred
)

mse = mean_squared_error(
    y_test,
    y_pred
)

rmse = np.sqrt(mse)

r2 = r2_score(
    y_test,
    y_pred
)

The predicted prices  are : [ 83.5200559  145.90133706  37.98677045 233.62699158 104.48198142]

In [23]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_model = LinearRegression()
poly_model.fit(x_train_poly,y_train)

poly = PolynomialFeatures(
    degree=2
)

x_train_poly = poly.fit_transform(
    x_train
)

x_test_poly = poly.transform(
    x_test
)
y_poly_pred = poly_model.predict(
    x_test_poly)
y_poly_pred
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

import numpy as np


poly_mae = mean_absolute_error(
    y_test,
    y_poly_pred
)


poly_mse = mean_squared_error(
    y_test,
    y_poly_pred
)


poly_rmse = np.sqrt(
    poly_mse
)


poly_r2 = r2_score(
    y_test,
    y_poly_pred
)


poly_mae, poly_mse, poly_rmse, poly_r2

(2.012803954584237,
 5.066246941921049,
 np.float64(2.2508324997478266),
 0.9988808721654441)

# Ridge Regression


Ridge Regression is a regularized version of Linear Regression.


Linear Regression tries to minimize only prediction error.


The cost function of Linear Regression is:


J(β) = Σ(y - ŷ)²



where:


y  → Actual value

ŷ  → Predicted value



Ridge Regression adds an additional penalty term to reduce large
coefficients.


The Ridge cost function is:


J(β) = Σ(y - ŷ)² + αΣβ²



The second term:


αΣβ²


is called L2 Regularization.


where:


α (alpha)

controls the strength of regularization.



β²

is the square of model coefficients.



Effect:


Small alpha:

Closer to Linear Regression


Large alpha:

More coefficient shrinkage



Ridge regression equation:


Price_lakhs =
β₀
+
β₁Area
+
β₂Bedrooms
+
β₃Age



but coefficients are calculated by minimizing:


Prediction Error + Coefficient Penalty

In [27]:
from sklearn.linear_model import Ridge


ridge_model = Ridge(
    alpha=1
)


ridge_model.fit(
    x_train,
    y_train
)

Ridge(alpha=1)

## Ridge Intercept


The intercept represents the constant term:


y = β₀ + β₁x₁ + β₂x₂ + β₃x₃



β₀ is the predicted value when all features are zero.


The trained Ridge model stores this value using:


model.intercept_

In [6]:
print(ridge_model.intercept_)

1.2598584010123517

## Ridge Coefficients


The coefficients represent the contribution of each feature towards
predicting the house price.


The feature order is:


X = [

Area_sqft,

Bedrooms,

Age_years

]



Therefore:


ridge_model.coef_[0]

→ Area coefficient


ridge_model.coef_[1]

→ Bedroom coefficient


ridge_model.coef_[2]

→ Age coefficient



Ridge minimizes coefficients because of the L2 penalty:


αΣβ²

In [7]:
print(ridge_model.coef_)

[ 0.04601704 -0.3141749  -0.08084262]

## Ridge Model Evaluation


After training, predictions are generated on unseen test data.


Prediction:


ŷ = Ridge Model(X_test)



Performance is evaluated using:


### MAE


MAE = (1/n)Σ|y - ŷ|



Measures average prediction error.



### MSE


MSE = (1/n)Σ(y - ŷ)²



Penalizes larger errors.



### RMSE


RMSE = √MSE



Same unit as house price.



### R²


R² = 1 - (SSres / SStot)



Measures how much variation is explained by the model.

In [28]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

import numpy as np


ridge_pred = ridge_model.predict(
    x_test
)


ridge_mae = mean_absolute_error(
    y_test,
    ridge_pred
)


ridge_mse = mean_squared_error(
    y_test,
    ridge_pred
)


ridge_rmse = np.sqrt(
    ridge_mse
)


ridge_r2 = r2_score(
    y_test,
    ridge_pred
)


ridge_mae, ridge_mse, ridge_rmse, ridge_r2

(3.713527330845095,
 17.21078747510297,
 np.float64(4.148588612420249),
 0.9961981578200154)

## Linear Regression vs Ridge Regression


Linear Regression coefficients:


model.coef_



Ridge Regression coefficients:


ridge_model.coef_



Ridge adds:


αΣβ²


to the cost function.


Therefore, coefficients usually become smaller.

In [10]:
comparison = pd.DataFrame(
    {
        "Feature": [
            "Area_sqft",
            "Bedrooms",
            "Age_years"
        ],
        "Linear Regression": model.coef_,
        "Ridge Regression": ridge_model.coef_
    }
)


comparison

     Feature  Linear Regression  Ridge Regression
0  Area_sqft           0.046184          0.046017
1   Bedrooms          -0.504495         -0.314175
2  Age_years          -0.089506         -0.080843

# Why does Ridge Regression shrink coefficients?
## Coefficient Shrinkage in Ridge


Ridge adds a penalty:


αΣβ²



During optimization, large coefficients increase the penalty value.


Therefore, the model tries to reduce coefficient magnitude.


The objective becomes:


Minimize:


Error + Penalty



The model balances:


1. Accurate predictions

2. Smaller coefficients



Because the penalty uses squared coefficients:


β²


large values are strongly punished.


Example:


Without Ridge:


β = 100



Penalty:


100² = 10000



With Ridge:


β = 10



Penalty:


10² = 100



Therefore, Ridge prefers smaller coefficients.

## Performance Comparison


Ridge Regression and Linear Regression are compared using:


RMSE

and

R² Score



RMSE:


Lower value indicates better prediction.



R²:


Higher value indicates better explanation of variance.



Ridge may perform better when:


- Dataset contains many features
- Features are correlated
- Linear Regression overfits



For simple datasets, Linear Regression may perform similarly or better.

In [13]:
model_comparison = pd.DataFrame(
    {
        "Model": [
            "Linear Regression",
            "Ridge Regression"
        ],
        "RMSE": [
            rmse,
            ridge_rmse
        ],
        "R2": [
            r2,
            ridge_r2
        ]
    }
)


model_comparison

               Model      RMSE        R2
0  Linear Regression  4.108732  0.996271
1   Ridge Regression  4.148589  0.996198

# Effect of Ridge Regularization


Ridge Regression controls model complexity using the parameter alpha.


The Ridge objective function is:


J(β) = Σ(y - ŷ)² + αΣβ²


where:


α controls the strength of regularization.


Small alpha:

The penalty is weak.

The model behaves similar to Linear Regression.



Large alpha:

The penalty becomes stronger.

Coefficients shrink more.



The purpose is to study how changing alpha affects:


1. Feature coefficients

2. Prediction error

3. Model performance

In [5]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import numpy as np
import pandas as pd


alpha_values = [0.01,0.1,1,10,100]


ridge_results = []


for alpha in alpha_values:

    ridge = Ridge(alpha=alpha)

    ridge.fit(
        x_train,
        y_train
    )

    pred = ridge.predict(
        x_test
    )

    rmse_value = np.sqrt(
        mean_squared_error(
            y_test,
            pred
        )
    )

    r2_value = r2_score(
        y_test,
        pred
    )

    ridge_results.append(
        [
            alpha,
            ridge.coef_[0],
            ridge.coef_[1],
            ridge.coef_[2],
            rmse_value,
            r2_value
        ]
    )

#### The results are stored in a table to observe the effect of alpha.

Columns:

Alpha:

Regularization strength


Area Coef:

Coefficient of Area_sqft


Bedrooms Coef:

Coefficient of Bedrooms


Age Coef:

Coefficient of Age_years


RMSE:

Prediction error


R²:

Model performance

In [6]:
ridge_alpha_table = pd.DataFrame(
    ridge_results,
    columns=[
        "Alpha",
        "Area Coef",
        "Bedrooms Coef",
        "Age Coef",
        "RMSE",
        "R2"
    ]
)


print(ridge_alpha_table)

    Alpha  Area Coef  Bedrooms Coef  Age Coef      RMSE        R2
0    0.01   0.046182      -0.501468 -0.089370  4.109353  0.996270
1    0.10   0.046159      -0.475766 -0.088210  4.114642  0.996260
2    1.00   0.046017      -0.314175 -0.080843  4.148589  0.996198
3   10.00   0.045808      -0.069586 -0.067934  4.204346  0.996095
4  100.00   0.045807      -0.006093 -0.049743  4.240954  0.996027

# Lasso Regression


Lasso Regression is another regularized regression technique.


Unlike Ridge which uses L2 penalty, Lasso uses L1 penalty.


Lasso cost function:


J(β)=Σ(y-ŷ)² + αΣ|β|



where:


|β|

represents absolute coefficient values.



Effect of Lasso:


- Reduces coefficient values
- Can make coefficients exactly zero
- Performs feature selection


Difference:


Ridge:

Shrinks coefficients


Lasso:

Shrinks and removes features

In [7]:
from sklearn.linear_model import Lasso


lasso_model = Lasso(
    alpha=1
)


lasso_model.fit(
    x_train,
    y_train
)

Lasso(alpha=1)

In [9]:
lasso_model.intercept_
lasso_model.coef_
lasso_pred = lasso_model.predict(
    x_test
)


lasso_mae = mean_absolute_error(
    y_test,
    lasso_pred
)


lasso_mse = mean_squared_error(
    y_test,
    lasso_pred
)


lasso_rmse = np.sqrt(
    lasso_mse
)


lasso_r2 = r2_score(
    y_test,
    lasso_pred
)


lasso_mae, lasso_mse, lasso_rmse, lasso_r2

(3.9211206236761966,
 18.67604807361642,
 np.float64(4.321579349452747),
 0.9958744835223602)

In [11]:
coefficient_table = pd.DataFrame(
    {
        "Feature":[
            "Area_sqft",
            "Bedrooms",
            "Age_years"
        ],
        "Linear":[
            model.coef_[0],
            model.coef_[1],
            model.coef_[2]
        ],
        "Ridge":[
            ridge.coef_[0],
            ridge.coef_[1],
            ridge.coef_[2]
        ],
        "Lasso":[
            lasso_model.coef_[0],
            lasso_model.coef_[1],
            lasso_model.coef_[2]
        ]
    }
)


coefficient_table

     Feature    Linear     Ridge     Lasso
0  Area_sqft  0.046184  0.045807  0.045977
1   Bedrooms -0.504495 -0.006093  0.000000
2  Age_years -0.089506 -0.049743 -0.000000

# Ridge vs Lasso


## Ridge Regression

Penalty:

αΣβ²


Effect:

- Coefficients become smaller
- No feature elimination



## Lasso Regression

Penalty:

αΣ|β|


Effect:

- Coefficients shrink
- Some coefficients can become exactly zero


A zero coefficient means:


The feature does not contribute significantly to prediction.


Therefore Lasso performs automatic feature selection.

In [14]:
lasso_results=[]


for alpha in alpha_values:

    lasso=Lasso(alpha=alpha)

    lasso.fit(
        x_train,
        y_train
    )

    pred=lasso.predict(
        x_test
    )


    rmse_value=np.sqrt(
        mean_squared_error(
            y_test,
            pred
        )
    )


    r2_value=r2_score(
        y_test,
        pred
    )


    lasso_results.append(
        [
            alpha,
            lasso.coef_[0],
            lasso.coef_[1],
            lasso.coef_[2],
            rmse_value,
            r2_value
        ]
    )

In [15]:
lasso_table=pd.DataFrame(
    lasso_results,
    columns=[
        "Alpha",
        "Area Coef",
        "Bedrooms Coef",
        "Age Coef",
        "RMSE",
        "R2"
    ]
)


lasso_table

    Alpha  Area Coef  Bedrooms Coef  Age Coef      RMSE        R2
0    0.01   0.046076      -0.379281 -0.083281  4.135492  0.996222
1    0.10   0.045764      -0.000000 -0.060132  4.226615  0.996054
2    1.00   0.045977       0.000000 -0.000000  4.321579  0.995874
3   10.00   0.045972       0.000000 -0.000000  4.323583  0.995871
4  100.00   0.045920       0.000000 -0.000000  4.344256  0.995831

# Lasso Regularization Analysis


As alpha increases:


Coefficients move towards zero.


Unlike Ridge:


Some coefficients may become exactly zero.



The first coefficient reaching zero indicates that feature is removed
from the model.



Comparison:


Ridge:

L2 penalty

Keeps all features


Lasso:

L1 penalty

Performs feature selection

# Final Model Comparison


Different regression models are evaluated using the same test dataset.


The models compared are:


1. Linear Regression

Uses original features and minimizes prediction error.



2. Polynomial Regression

Creates additional polynomial features to capture nonlinear patterns.



3. Ridge Regression

Uses L2 regularization to reduce coefficient magnitude.



4. Lasso Regression

Uses L1 regularization and can perform feature selection.



Evaluation Metrics:


MAE:

Average absolute prediction error.



MSE:

Average squared prediction error.



RMSE:

Square root of MSE.

Lower RMSE indicates better performance.



R² Score:

Measures the percentage of variance explained by the model.

Higher R² indicates better performance.

In [29]:
final_results = pd.DataFrame(
    {
        "Model":[
            "Linear Regression",
            "Polynomial Regression",
            "Ridge Regression",
            "Lasso Regression"
        ],

        "MAE":[
            mae,
            poly_mae,
            ridge_mae,
            lasso_mae
        ],

        "MSE":[
            mse,
            poly_mse,
            ridge_mse,
            lasso_mse
        ],

        "RMSE":[
            rmse,
            poly_rmse,
            ridge_rmse,
            lasso_rmse
        ],

        "R2":[
            r2,
            poly_r2,
            ridge_r2,
            lasso_r2
        ]
    }
)


final_results

                   Model       MAE        MSE      RMSE        R2
0      Linear Regression  3.657922  16.881677  4.108732  0.996271
1  Polynomial Regression  2.012804   5.066247  2.250832  0.998881
2       Ridge Regression  3.713527  17.210787  4.148589  0.996198
3       Lasso Regression  3.921121  18.676048  4.321579  0.995874

# Final Analysis Questions


## 1. Best Predictive Model

The best predictive model is Polynomial Regression.

It achieved:

- Lowest RMSE = 2.250832
- Lowest MAE = 2.012804
- Lowest MSE = 5.066247

It also achieved the highest R² score:

R² = 0.998881


Therefore, Polynomial Regression is selected as the best predictive
model because it produces the most accurate predictions on the test
dataset.

The reason for its better performance is that polynomial features allow
the model to capture nonlinear relationships between house features and
price.

## 2. Best Model Based on R²


Polynomial Regression gives the highest R² score:

R² = 0.998881


This means that the model explains approximately 99.88% of the variation
in house prices.


However, the highest R² score alone does not always mean the model is
best for deployment.


A complex model may perform very well on training data but may overfit
and fail on new unseen data.


Therefore, model selection should consider:

- RMSE
- MAE
- R²
- Generalization ability

## 3. Coefficient Shrinkage


Linear Regression calculates coefficients by minimizing only prediction
error.


Ridge Regression adds an L2 regularization penalty:


J(β) = Σ(y - ŷ)² + αΣβ²


Because of this penalty, Ridge reduces the magnitude of coefficients.


Observation:

- Linear Regression has larger coefficients.
- Ridge Regression has smaller coefficients.


This helps reduce overfitting and improves model stability.

## 4. Feature Selection


Ridge and Lasso both use regularization, but their effects are different.


Ridge Regression:

- Uses L2 regularization.
- Shrinks coefficients.
- Does not make coefficients exactly zero.
- Keeps all features.


Lasso Regression:

- Uses L1 regularization.
- Can reduce some coefficients exactly to zero.
- Performs automatic feature selection.


A zero coefficient means that the corresponding feature does not
contribute significantly to the prediction.


This is useful when datasets contain many features because Lasso can
remove unnecessary features and create a simpler model.

## 5. Regularization Parameter


Alpha controls the strength of regularization.


### Ridge Regression


When alpha increases:

- The L2 penalty becomes stronger.
- Coefficients shrink more.
- Model complexity decreases.
- Very high alpha can cause underfitting.



### Lasso Regression


When alpha increases:

- The L1 penalty becomes stronger.
- More coefficients move towards zero.
- Some features may be completely removed.


Therefore:

Small alpha → Less regularization

Large alpha → Stronger regularization

## 6. Conceptual Comparison


| Model | Cost Function | Main Effect |
|---|---|---|
| Linear Regression | Σ(y - ŷ)² | Minimizes prediction error |
| Ridge Regression | Σ(y - ŷ)² + αΣβ² | Shrinks coefficients |
| Lasso Regression | Σ(y - ŷ)² + αΣ|β| | Performs feature selection |


Polynomial Regression changes the input features by creating new
features such as:

- Area²
- Bedrooms²
- Age²
- Area × Bedrooms


Ridge and Lasso do not change the features.

They modify the objective function used to estimate coefficients.

## 7. Final Question


"Polynomial Regression changes the features used by the model, whereas
Ridge and Lasso change the objective function used to estimate the
coefficients."


Explanation:


Polynomial Regression creates additional features from existing
features.

Example:

Area

becomes:

Area

Area²

Area × Bedrooms


The model receives a new feature representation.


Ridge and Lasso keep the same features but modify the optimization
process.


Ridge adds an L2 penalty:

αΣβ²


Lasso adds an L1 penalty:

αΣ|β|


Therefore:


Polynomial Regression:

Changes the input representation.


Ridge/Lasso:

Change how coefficients are calculated.