## Question 1: Load CSV File

The dataset is loaded using Pandas.
We will inspect:
- first 5 rows
- last 5 rows
- dataset shape
- column names
- data types

### Explanation

`df.head()` displays the first 5 rows.

It helps us verify:
- whether data is loaded correctly
- column names
- sample values

In [10]:
import pandas as pd
df = pd.read_csv("house_regression_lab_dataset(in).csv")
df.head(5)

   Area_sqft  Bedrooms  Age_years  Price_lakhs
0        850         2         22           42
1        950         2         18           46
2       1100         2         25           50
3       1200         3         15           57
4       1350         3         12           63

### tail()

`tail()` displays the last 5 rows.

It helps check:
- End of dataset
- Whether rows are missing or corrupted

In [9]:
import pandas as pd
df = pd.read_csv("house_regression_lab_dataset(in).csv")
df.tail(5)

    Area_sqft  Bedrooms  Age_years  Price_lakhs
20       4200         6          7          190
21       4500         6          2          205
22       4800         6          5          218
23       5100         7          1          238
24       5500         7          3          255

### Dataset Shape

`shape` returns:

(number of rows, number of columns)

Example:

(100,4)

means:
- 100 house samples
- 4 columns

Columns include:
- 3 features
- 1 target variable

In [13]:
import pandas as pd
df = pd.read_csv("house_regression_lab_dataset(in).csv")
df.shape

(25, 4)

### Column Names

Column names tell us the available features.

Later we separate:

X = input features

y = output prediction target

In [14]:
import pandas as pd
df = pd.read_csv("house_regression_lab_dataset(in).csv")
df.columns

Index(['Area_sqft', 'Bedrooms', 'Age_years', 'Price_lakhs'], dtype='str')

### Data Types

Checking data types helps identify:

- Numerical columns
- Categorical columns
- Possible conversion problems

Machine learning models require numerical inputs.

In [15]:
import pandas as pd
df = pd.read_csv("house_regression_lab_dataset(in).csv")
df.dtypes

Area_sqft      int64
Bedrooms       int64
Age_years      int64
Price_lakhs    int64
dtype: object

##  Missing Value Checking and Feature Selection

Before building a machine learning model, we need to check whether
the dataset contains missing values.

Missing values can cause errors during model training because most
machine learning algorithms cannot directly handle NaN values.

After checking missing values, we separate:

Independent Variables (Features):
X = [Area_sqft, Bedrooms, Age_years]

Target Variable:
y = Price_lakhs

The model learns the relationship between X and y.

### isnull()

`isnull()` checks every cell in the dataset.

Output:
- True  → value is missing
- False → value is present

Example:

Area_sqft | Bedrooms | Age_years | Price_lakhs
---|---|---|---
1200 | 2 | 10 | False
1500 | NaN | 5 | True
### Counting Missing Values

`sum()` counts the number of True values column-wise.

Example output:

Area_sqft       0
Bedrooms        2
Age_years       0
Price_lakhs     0

This means:
- Area_sqft has no missing values
- Bedrooms has 2 missing values

In [17]:
import pandas as pd
df = pd.read_csv("house_regression_lab_dataset(in).csv")
print(df.isnull())
print(df.isnull().sum())

    Area_sqft  Bedrooms  Age_years  Price_lakhs
0       False     False      False        False
1       False     False      False        False
2       False     False      False        False
3       False     False      False        False
4       False     False      False        False
5       False     False      False        False
6       False     False      False        False
7       False     False      False        False
8       False     False      False        False
9       False     False      False        False
10      False     False      False        False
11      False     False      False        False
12      False     False      False        False
13      False     False      False        False
14      False     False      False        False
15      False     False      False        False
16      False     False      False        False
17      False     False      False        False
18      False     False      False        False
19      False     False      False        False
20      False     False      False        False
21      False     False      False        False
22      False     False      False        False
23      False     False      False        False
24      False     False      False        False
Area_sqft      0
Bedrooms       0
Age_years      0
Price_lakhs    0
dtype: int64

### Feature Selection

X contains the input variables given to the machine learning model.

Here:

X = [
    Area_sqft,
    Bedrooms,
    Age_years
]

These variables are used to predict house price.

Example:

Input:

Area = 1500 sqft
Bedrooms = 3
Age = 5 years


Output:

Price = 120 lakhs

### Target Variable

y is the value that the model tries to predict.

Here:

y = Price_lakhs

The regression model learns:

Area + Bedrooms + Age
             |
             ↓
       House Price

In [21]:
import pandas as pd
df = pd.read_csv("house_regression_lab_dataset(in).csv")
x= df[["Area_sqft", "Bedrooms", "Age_years"]]
y = df["Price_lakhs"]
print("Input features with values:")
print(x.head())
print("Target feature :")
print(y.head())

Input features with values:
   Area_sqft  Bedrooms  Age_years
0        850         2         22
1        950         2         18
2       1100         2         25
3       1200         3         15
4       1350         3         12
Target feature :
0    42
1    46
2    50
3    57
4    63
Name: Price_lakhs, dtype: int64

## Splitting Dataset into Training and Testing Data

Machine learning models should not be evaluated on the same data
used for training.

Therefore, we split the dataset into:

Training Data:
80%

Used to learn patterns.

Testing Data:
20%

Used to evaluate model performance.

Parameters:
- test_size = 0.2
- random_state = 42

### Parameters

X:
Input features

y:
Target values

test_size=0.2:

20% data goes to testing.

Remaining 80% goes to training.


random_state=42:

Controls randomness.

Using the same value gives the same split every time.

In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split
df = pd.read_csv("house_regression_lab_dataset(in).csv")
x= df[["Area_sqft", "Bedrooms", "Age_years"]]
y = df["Price_lakhs"]

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)


print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(20, 3)
(5, 3)
(20,)
(5,)